version: "3"
services:
  mongo:
    image: "mongo"
    hostname: "mongo1"
    ports:
      - "27020:27017"
    healthcheck:
    test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
    networks:
      - mongodb_network
    volumes:
      - mongo-data:/data/db
  api:
    image: rms-backend-api:latest
    hostname: rms-backend-api
    # build: .
    # command: npm run prod-start
    ports:
      - "8083:8083"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
volumes:
  mongo-data:

networks:
  mongodb_network:
    driver: overlay
